"""Compatibility shim for :mod:`gem.results.models`."""

from gem.results.models import (
    AegisEvent,
    BarracksKill,
    ChatEntry,
    CombatLogEntry,
    CourierSnapshot,
    DraftEvent,
    NeutralItemFoundEvent,
    ParsedMatch,
    ParsedPlayer,
    RoshanKill,
    ShrineKill,
    SmokeEvent,
    Teamfight,
    TormentorKill,
    TowerKill,
    VisionModifierEvent,
    WardEvent,
    dataclass,
    defaultdict,
    field,
)

__all__ = [
    "AegisEvent",
    "BarracksKill",
    "ChatEntry",
    "CombatLogEntry",
    "CourierSnapshot",
    "DraftEvent",
    "NeutralItemFoundEvent",
    "ParsedMatch",
    "ParsedPlayer",
    "RoshanKill",
    "ShrineKill",
    "SmokeEvent",
    "Teamfight",
    "TormentorKill",
    "TowerKill",
    "VisionModifierEvent",
    "WardEvent",
    "dataclass",
    "defaultdict",
    "field",
]
