# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uifontfile_format.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 2, "", "uifontfile_format.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17uifontfile_format.proto"C\n\rCUIFontFilePB\x12\x16\n\x0e\x66ont_file_name\x18\x01 \x01(\t\x12\x1a\n\x12opentype_font_data\x18\x02 \x01(\x0c"\xb1\x01\n\x14\x43UIFontFilePackagePB\x12\x17\n\x0fpackage_version\x18\x01 \x02(\r\x12J\n\x14\x65ncrypted_font_files\x18\x02 \x03(\x0b\x32,.CUIFontFilePackagePB.CUIEncryptedFontFilePB\x1a\x34\n\x16\x43UIEncryptedFontFilePB\x12\x1a\n\x12\x65ncrypted_contents\x18\x01 \x01(\x0c'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "uifontfile_format_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CUIFONTFILEPB"]._serialized_start = 27
    _globals["_CUIFONTFILEPB"]._serialized_end = 94
    _globals["_CUIFONTFILEPACKAGEPB"]._serialized_start = 97
    _globals["_CUIFONTFILEPACKAGEPB"]._serialized_end = 274
    _globals["_CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB"]._serialized_start = 222
    _globals["_CUIFONTFILEPACKAGEPB_CUIENCRYPTEDFONTFILEPB"]._serialized_end = 274
# @@protoc_insertion_point(module_scope)
