# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_gcmessages_common.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'event_gcmessages_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65vent_gcmessages_common.proto\"@\n\x0f\x43MsgEventAction\x12\x11\n\taction_id\x18\x01 \x01(\r\x12\x1a\n\x0ftimes_completed\x18\x02 \x01(\r:\x01\x31\"\xed\x01\n\x13\x43MsgUserEventPoints\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\r\x12\x14\n\x0ctotal_points\x18\x03 \x01(\r\x12\x1c\n\x14total_premium_points\x18\x04 \x01(\r\x12\x0e\n\x06points\x18\x05 \x01(\r\x12\x16\n\x0epremium_points\x18\x06 \x01(\r\x12+\n\x11\x63ompleted_actions\x18\x07 \x03(\x0b\x32\x10.CMsgEventAction\x12\r\n\x05owned\x18\x08 \x01(\x08\x12\x18\n\x10\x61\x63tive_season_id\x18\t \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_gcmessages_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CMSGEVENTACTION']._serialized_start=33
  _globals['_CMSGEVENTACTION']._serialized_end=97
  _globals['_CMSGUSEREVENTPOINTS']._serialized_start=100
  _globals['_CMSGUSEREVENTPOINTS']._serialized_end=337
# @@protoc_insertion_point(module_scope)
