"""Post-parse analysis helpers for gem replay data."""

from gem._deprecation import deprecated_module_attrs, renamed_module_attrs
from gem.analysis.abilities import ability_level_at_tick
from gem.analysis.bundle import MatchAnalysis, analyze
from gem.analysis.combat import (
    AbilityCast,
    fight_at_tick,
    find_fights,
    group_ability_hits,
    is_active_fight_participant,
)
from gem.analysis.farming import (
    DEFAULT_FARMING_CONTEXT_CONFIG,
    DEFAULT_FARMING_ROUTE_CONFIG,
    FarmingBoundaryReason,
    FarmingCampZone,
    FarmingContextConfig,
    FarmingContextTag,
    FarmingEvidenceStrength,
    FarmingRoute,
    FarmingRouteConfig,
    FarmingRoutePoint,
    FarmingRouteSegment,
    FarmingSegmentContext,
    build_farming_routes,
)
from gem.analysis.fight_positioning import (
    EngagementStartSource,
    EvidenceCompleteness,
    FightPositioning,
    FightPositionSnapshot,
    HeroPositionEvidence,
    SnapshotKind,
    TeamPositionSummary,
    build_fight_positioning,
)
from gem.analysis.formatting import format_npc_name
from gem.analysis.map_context import (
    CampVisitContext as _CampVisitContext,
    MapContextBucket as _MapContextBucket,
    build_map_context_timeline as _build_map_context_timeline,
    score_camp_visit_context as _score_camp_visit_context,
    world_in_bounds as _world_in_bounds,
)
from gem.analysis.roshan import (
    DEFAULT_ROSH_TAG_THRESHOLDS,
    AegisFateSource,
    RoshConversion,
    RoshCoverageCell,
    RoshDifferentialProfile,
    RoshFightEvidence,
    RoshFightRelation,
    RoshTagThresholds,
    RoshTeamAttributionSource,
    RoshTerritoryConfig,
    RoshTerritoryWindow,
    RoshTimelineEvent,
    build_rosh_conversions,
)
from gem.analysis.smoke import (
    SmokeAnalysis,
    SmokeGroupStatus,
    SmokeLifecycleStatus,
    SmokeMemberAnalysis,
    build_smoke_analysis,
)
from gem.analysis.smoke_fight import (
    ExactEventEvidence,
    ExactEventKind,
    FightCentroidSource,
    FightOutcome,
    FollowUpBoundary,
    FollowUpEvent,
    FollowUpKind,
    FollowUpWindow,
    FormationEvidence,
    MemberPositionEvidence,
    SampledNearFightEvidence,
    SmokeFightInsight,
    SmokeFightMemberInsight,
    SmokeFightStatus,
    TeamRelation,
    build_smoke_fight_insights,
)
from gem.analysis.spatial import (
    SampledPosition,
    heroes_near,
    net_worth_at,
    position_at_tick,
    position_sample_at_tick,
)
from gem.analysis.vision import (
    DirectTargetRevealEvidence,
    PointVisionAssessment,
    PointVisionGap,
    PointVisionSource,
    PointVisionStatus,
    VisionSource,
    _is_daytime,
    assess_point_vision,
    entity_visibility_at,
    estimate_vision as _estimate_vision,
    hero_visibility_at,
    is_daytime,
    ward_vision_impact,
)

__all__ = [
    "AbilityCast",
    "AegisFateSource",
    "DEFAULT_FARMING_CONTEXT_CONFIG",
    "DEFAULT_FARMING_ROUTE_CONFIG",
    "DirectTargetRevealEvidence",
    "DEFAULT_ROSH_TAG_THRESHOLDS",
    "EngagementStartSource",
    "EvidenceCompleteness",
    "ExactEventEvidence",
    "ExactEventKind",
    "FightCentroidSource",
    "FightOutcome",
    "FightPositionSnapshot",
    "FarmingBoundaryReason",
    "FarmingCampZone",
    "FarmingContextConfig",
    "FarmingContextTag",
    "FarmingEvidenceStrength",
    "FarmingRoute",
    "FarmingRouteConfig",
    "FarmingRoutePoint",
    "FarmingRouteSegment",
    "FarmingSegmentContext",
    "HeroPositionEvidence",
    "FollowUpBoundary",
    "FollowUpEvent",
    "FollowUpKind",
    "FollowUpWindow",
    "FormationEvidence",
    "MemberPositionEvidence",
    "PointVisionAssessment",
    "PointVisionGap",
    "PointVisionSource",
    "PointVisionStatus",
    "RoshConversion",
    "RoshCoverageCell",
    "RoshDifferentialProfile",
    "RoshFightEvidence",
    "RoshFightRelation",
    "RoshTagThresholds",
    "RoshTeamAttributionSource",
    "RoshTerritoryConfig",
    "RoshTerritoryWindow",
    "RoshTimelineEvent",
    "SmokeAnalysis",
    "SampledNearFightEvidence",
    "SmokeFightInsight",
    "SmokeFightMemberInsight",
    "SmokeFightStatus",
    "SmokeGroupStatus",
    "SmokeLifecycleStatus",
    "SmokeMemberAnalysis",
    "SnapshotKind",
    "TeamPositionSummary",
    "TeamRelation",
    "FightPositioning",
    "SampledPosition",
    "VisionSource",
    "_is_daytime",
    "ability_level_at_tick",
    "assess_point_vision",
    "build_farming_routes",
    "build_rosh_conversions",
    "build_smoke_analysis",
    "build_smoke_fight_insights",
    "build_fight_positioning",
    "MatchAnalysis",
    "analyze",
    "entity_visibility_at",
    "hero_visibility_at",
    "format_npc_name",
    "group_ability_hits",
    "heroes_near",
    "is_active_fight_participant",
    "is_daytime",
    "net_worth_at",
    "position_at_tick",
    "position_sample_at_tick",
    "fight_at_tick",
    "find_fights",
    "ward_vision_impact",
]

#: Names gem 0.10 and earlier used for gem's own fights.
RENAMED_FIGHT_NAMES = {
    "TeamfightPositioning": "FightPositioning",
    "build_teamfight_positioning": "build_fight_positioning",
    "is_active_teamfight_participant": "is_active_fight_participant",
    "teamfight_at_tick": "fight_at_tick",
}

_MAP_CONTEXT_ALTERNATIVE = "the match's wards, towers and position data"

#: Names deprecated in 0.12 and removed in 0.13 (HY-96), served with a warning:
#: name -> (object, alternative, warn on access). Functions warn when called.
DEPRECATED_ANALYSIS_NAMES = {
    "CampVisitContext": (_CampVisitContext, None, True),
    "MapContextBucket": (_MapContextBucket, _MAP_CONTEXT_ALTERNATIVE, True),
    "build_map_context_timeline": (_build_map_context_timeline, None, False),
    "score_camp_visit_context": (_score_camp_visit_context, None, False),
    "world_in_bounds": (_world_in_bounds, None, False),
    "estimate_vision": (_estimate_vision, None, False),
}

__getattr__ = deprecated_module_attrs(
    __name__,
    DEPRECATED_ANALYSIS_NAMES,
    renamed_module_attrs(__name__, RENAMED_FIGHT_NAMES, globals()),
)
